# Numpy

**NUMPY**


- COMPUTAÇÃO CIENTÍFICA: FALICITAM OPERAÇÕES MATEMÁTICAS AVANÇADAS E OUTROS TIPOS DE OPERAÇÕES EM MUITOS DADOS;

- OBJETO DE MATRIZ MULTIDIMENSIONAL;

- VARIEDADE DE ROTINAS PARA OPERAÇÕES RÁPIDAS EM MATRIZES;

- OS ARRAYS NUMPY TÊM UM TAMANHO FIXO NA CRIAÇÃO, AO CONTRÁRIO DAS LISTAS PYTHON (QUE PODEM CRESCER DINAMICAMENTE).

In [ ]:
import numpy as np

In [ ]:
# criando uma matriz unidimensional
mt = np.array([12, 34, 26, 18, 10])

In [ ]:
mt

array([12, 34, 26, 18, 10])

In [ ]:
type(mt)

numpy.ndarray

In [ ]:
# criando um array com um tipo específico pelo parâmetro dtype
mtfloat = np.array([1, 2, 3], dtype = np.float64) # nesse exemplo o tipo do dado é float
mtfloat

array([1., 2., 3.])

In [ ]:
type(mtfloat)

numpy.ndarray

In [ ]:
mtint = np.array([1.0, 2.6, 4.1], dtype = np.int32) # tipo int
mtint

array([1, 2, 4], dtype=int32)

In [ ]:
type(mtint)

numpy.ndarray

In [ ]:
# criando uma matriz bidimensional
# cada lista representa uma linha na matriz
mt2 = np.array([[7,2,23],[12,27,4],[5,34,23]])
print(mt2)

[[ 7  2 23]
 [12 27  4]
 [ 5 34 23]]


In [ ]:
type(mt2)

numpy.ndarray

In [ ]:
# remoção de itens repetidos com np.unique()
rep = np.array([11, 12, 13, 14, 15, 11, 12, 16, 20, 16, 30])
np.unique(rep)

In [ ]:
# selecionando um item específio na matriz, através de sua localização por linha e coluna
k = np.array([[7,2,23],[12,27,4],[5,34,23]])
k

In [ ]:
# linha 1, coluna 3
k[0][2]

In [ ]:
# funções matemáticas
# maior valor da matriz
print(k.max())

# menor valor da matriz
print(k.min())

# soma dos valores da matriz
print(k.sum())

# média dos valores da matriz
print(k.mean())

# mostra o valor do desvio padrão dos valores da matriz
print(k.std())

In [ ]:
# raiz quadrada de todos os elementos
k1 = np.array([1, 4, 9, 16, 25, 36])
print(np.sqrt(k1))

# valor exponencial de todos os elementos
print(np.exp(k1))

In [ ]:
# extração de elementos
m = np.array([1, 2, 3, 4, 5, 6])
print(m[1]) # segundo elemento

# elemento de índice 0 até 1
print(m[0:2])

# elemento de índice 1 até o final
print(m[1:])

# penúltimo elemento em diante
print(m[-2:])


In [ ]:
# extração de linhas e colunas
df = np.array([[4, 5], [6, 1], [7, 4]])
print(df)
print('----------------')

# primeira linha e todas as colunas
print(df[0,:])
print('----------------')

# segunda linha
print(df[1])
print('----------------')

# terceira linha
print(df[2])
print('----------------')

# todas as linhas, primeira coluna
print(df[:, 0])
print('----------------')

# todas as linhas, segunda coluna
print(df[:,1])

In [ ]:
# adição e multiplicação de matrizes
n = np.array([[1, 2], [3, 4]])
o = np.array([[1, 1], [1, 1]])

# soma
print(n+o)
print("-------")

# multiplicação
print(n*o)
print("-------")

In [ ]:
# transposição, organizando um conjunto de 15 elementos de 0 a 14
# em 3 linhas e 5 colunas
f = np.arange(15).reshape((3,5))
print(f)
print("-------")

# transposição da matriz f
print(f.T)