# Numpy

**NUMPY**


- COMPUTAÇÃO CIENTÍFICA: FALICITAM OPERAÇÕES MATEMÁTICAS AVANÇADAS E OUTROS TIPOS DE OPERAÇÕES EM MUITOS DADOS;

- OBJETO DE MATRIZ MULTIDIMENSIONAL;

- VARIEDADE DE ROTINAS PARA OPERAÇÕES RÁPIDAS EM MATRIZES;

- OS ARRAYS NUMPY TÊM UM TAMANHO FIXO NA CRIAÇÃO, AO CONTRÁRIO DAS LISTAS PYTHON (QUE PODEM CRESCER DINAMICAMENTE).

In [1]:
# importando o módulo Numpy

import numpy as np

In [2]:
# criando uma matriz unidimensional
mt = np.array([12, 34, 26, 18, 10])

In [3]:
mt

array([12, 34, 26, 18, 10])

In [4]:
type(mt)

numpy.ndarray

In [5]:
# criando um array com um tipo específico pelo parâmetro dtype
mtfloat = np.array([1, 2, 3], dtype = np.float64) # nesse exemplo o tipo do dado é float
mtfloat

array([1., 2., 3.])

In [6]:
type(mtfloat)

numpy.ndarray

In [7]:
mtint = np.array([1.0, 2.6, 4.1], dtype = np.int32) # tipo int
mtint

array([1, 2, 4], dtype=int32)

In [8]:
type(mtint)

numpy.ndarray

In [9]:
# criando uma matriz bidimensional
# cada lista representa uma linha na matriz
mt2 = np.array([[7,2,23],[12,27,4],[5,34,23]])
print(mt2)

[[ 7  2 23]
 [12 27  4]
 [ 5 34 23]]


In [10]:
type(mt2)

numpy.ndarray

In [11]:
# remoção de itens repetidos com np.unique()
rep = np.array([11, 12, 13, 14, 15, 11, 12, 16, 20, 16, 30])
np.unique(rep)

array([11, 12, 13, 14, 15, 16, 20, 30])

In [12]:
# selecionando um item específio na matriz, através de sua localização por linha e coluna
k = np.array([[7,2,23],[12,27,4],[5,34,23]])
k

array([[ 7,  2, 23],
       [12, 27,  4],
       [ 5, 34, 23]])

In [13]:
# linha 1, coluna 3
k[0][2]

23

In [14]:
# funções matemáticas
# maior valor da matriz
print(k.max())

# menor valor da matriz
print(k.min())

# soma dos valores da matriz
print(k.sum())

# média dos valores da matriz
print(k.mean())

# mostra o valor do desvio padrão dos valores da matriz
print(k.std())

34
2
137
15.222222222222221
11.033059188716807


In [15]:
# raiz quadrada de todos os elementos
k1 = np.array([1, 4, 9, 16, 25, 36])
print(np.sqrt(k1))

# valor exponencial de todos os elementos
print(np.exp(k1))

[1. 2. 3. 4. 5. 6.]
[2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06
 7.20048993e+10 4.31123155e+15]


In [16]:
# extração de elementos
m = np.array([1, 2, 3, 4, 5, 6])
print(m[1]) # segundo elemento

# elemento de índice 0 até 1
print(m[0:2])

# elemento de índice 1 até o final
print(m[1:])

# penúltimo elemento em diante
print(m[-2:])


2
[1 2]
[2 3 4 5 6]
[5 6]


In [17]:
# extração de linhas e colunas
df = np.array([[4, 5], [6, 1], [7, 4]])
print(df)
print('----------------')

# primeira linha e todas as colunas
print(df[0,:])
print('----------------')

# segunda linha
print(df[1])
print('----------------')

# terceira linha
print(df[2])
print('----------------')

# todas as linhas, primeira coluna
print(df[:, 0])
print('----------------')

# todas as linhas, segunda coluna
print(df[:,1])

[[4 5]
 [6 1]
 [7 4]]
----------------
[4 5]
----------------
[6 1]
----------------
[7 4]
----------------
[4 6 7]
----------------
[5 1 4]


In [18]:
# adição e multiplicação de matrizes
n = np.array([[1, 2], [3, 4]])
o = np.array([[1, 1], [1, 1]])

# soma
print(n+o)
print("-------")

# multiplicação
print(n*o)
print("-------")

[[2 3]
 [4 5]]
-------
[[1 2]
 [3 4]]
-------


In [19]:
# transposição, organizando um conjunto de 15 elementos de 0 a 14
# em 3 linhas e 5 colunas
f = np.arange(15).reshape((3,5))
print(f)
print("-------")

# transposição da matriz f
print(f.T)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
-------
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]
